### ISSUE TITLE
Broken sponsor logos

### ISSUE THREAD

**Issue by stanzheng** [norfolkjs/norfolkjs.github.io#75]
some sponsor logos break sometime? 

http://norfolkjs.org/sponsors

**Comment by stanzheng** [comment]
edit: it looks fine now but its intermittent,

**Comment by tjwebb** [comment]
post output of your chrome debugger network tab; otherwise "broken" has no meaning.

close for now?

**Comment by stanzheng** [comment]
yeah sorry, i wanted to jot it down as a later reminder.

some of the images break from meetup and dont log in but it doesn't happen all the time.

If i can actually narrow it down ill reopen

**Comment by tjwebb** [comment]
Ok, thanks.
