### ISSUE TITLE
Post video recordings if available

### ISSUE THREAD

**Issue by codingcampbell** [norfolkjs/norfolkjs.github.io#80]
As a serial absentee to these meetings, I'm thrilled @pchinjr managed to capture some of them:

https://www.youtube.com/watch?v=Xw9Hb1EWmX8
https://www.youtube.com/watch?v=xQKB3lsUL4k

Assuming Paul and the presenters give the OK, it would be great to see these on the website. It also wouldn't hurt to update the old meetups with a link to the video (and slides, too, since most publish after the talk anyway)

**Comment by pchinjr** [comment]
I will create a new post on the blog with the videos when they are completed.

**Comment by bmf** [comment]
Recordings are up. Closing Issue.
