### ISSUE TITLE
Update Sponsors page

### ISSUE THREAD

**Issue by bmf** [norfolkjs/norfolkjs.github.io#84]
Pierce/McCoy is listed twice and No Starch Press needs to be removed.

**Comment by lynnaloo** [comment]
They responded to Travis this week with a new contact so it's worth leaving No Starch Press on there for now.

**Comment by stanzheng** [comment]
They are twice as awesome but I've removed one of the P/M entries

**Comment by bmf** [comment]
Sweet. Easiest update yet.
